"""empty message

Revision ID: 45a38970a1e5
Revises: 
Create Date: 2019-12-27 02:04:36.450309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45a38970a1e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nearbyrestaurants')
    op.alter_column('restaurants', 'city',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('restaurants', 'state',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('restaurants', 'street_address',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('users', 'street_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('street_address', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('restaurants', 'street_address',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('restaurants', 'state',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('restaurants', 'city',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.create_table('nearbyrestaurants',
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.restaurant_id'], name='nearbyrestaurants_restaurant_id_fkey'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], name='nearbyrestaurants_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', 'restaurant_id', name='nearbyrestaurants_pkey')
    )
    # ### end Alembic commands ###
